Work around `(enabled_if ...)` not working properly in dune
    ➜  eio git:(main) ✗ dune build
    File "lib_eio_linux/tests/dune", line 30, characters 21-30:
    30 |  (libraries alcotest eio_linux))
                              ^^^^^^^^^
    Error: Library "eio_linux" in _build/default/lib_eio_linux is hidden
    (unsatisfied 'enabled_if').
    -> required by _build/default/lib_eio_linux/tests/test.exe
    -> required by alias lib_eio_linux/tests/all
    -> required by alias default