Allow `eio_linux` package to be empty using `(allow_empty)`
The use of undocumented `(allow_empty)` was suggested by dune:

    ➜  eio git:(main) ✗ dune build
    Error: The package eio_linux does not have any user defined stanzas attached
    to it. If this is intentional, add (allow_empty) to the package definition in
    the dune-project file
    -> required by _build/default/eio_linux.install
    -> required by alias all
    -> required by alias default