Windows: fix "unavailable signal" error
Only try to ignore sigpipe signals on Unix-type systems. Otherwise, it
fails with:

    Fatal error: exception Invalid_argument("Sys.signal: unavailable signal")

Also, delay doing this until `Eio_luv.run` is called so merely linking
with `Eio_luv` doesn't change the behaviour of your program.

Reported-by: Nicolás Ojeda Bär